Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2021-10, with the labels that each got.

#414 Change: Make Hellfire Drone Kills Reward XP Like Battle Drones
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Controversial

#276 Fix: GPS Scrambled Rangers And Red Guards Remain Stealthed While Capturing Buildings; Same For Non-Infantry General Hackers Disabling Buildings
  Patch104pZH/Design/Tasks/commy2_tasks.txt
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug

#440 Fix: Demo Traps Are Triggered By Nearby Enemy Poison And Radiation Fields
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug

#441 Fix: Units Shooting Fuel Air Bomb Gas Cloud
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Bug

#442 Fix: ECM Tank Cannot Disable Heroic (Vet 3) Quad Cannons
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug

#443 Fix: Scaffolds Delete Money Crates
  Patch104pZH/GameFilesEdited/Data/INI/Crate.ini
Labels: Design, Controversial

#444 Add information for git on how to delete big file history to reduce size of repository
  Documents/git/removing-large-files-git-bfg.md
Labels: Documentation

#448 Add latest and missing changes to game fixes document
  Patch104pZH/Design/Changes/game_fixes.md
Labels: Documentation

#485 Add game audio file information
  Documents/Audio/audio.md
Labels: Documentation

#456 Fix: Boss General King Raptor Issues
  Patch104pZH/Design/Tasks/commy2_tasks.txt
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
Labels: Bug

#512 Fix: GLA02 Campaign Stealth General Base Defense Issues
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
Labels: Bug

#514 Fix: GLA02 Campaign Stealth General Building Issues
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
Labels: Bug

#563 Fix: Demo General Advanced Demo Trap Uses Model Of Normal Demo Trap When Build Or Sold
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
Labels: Bug

#547 Change: Let Saboteurs Enter Supply Drop Zones And Black Markets (Steal $1000)
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Design, Controversial

#544 Fix: Stealth General Saboteur Cannot Disable Internet Centers And Destroy Fake Buildings
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Controversial

#538 Fix: Powered Arms Dealer Door Still Open When Chain Building Technicals and Combat Bikes
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug

#571 Add: Implemention Of Radar Station Tech Building As Prop
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
Labels: Design

#568 Fix: Reinforcement Pad Is Deleted When Destroyed; Does Not Leave Ruin Like Other Tech Buildings
  Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
Labels: Bug

#572 Add: Mammoth Tank Default Implementation With Textures From CCG Alpha Version
  Patch104pZH/GameFilesEdited/Art/Textures/gxmammoth_co.tga
  Patch104pZH/GameFilesEdited/Art/Textures/gxmammothalt_HI.tga
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
  Patch104pZH/Scripts/MAKE_Patch104pZH.bat
Labels: Design
