Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2022-09, with the labels that each got.

#1062 Rename language bundle items
  Patch104pZH/ModBundleItems.json
  Patch104pZH/ModBundlePacks.json
Labels: Patch104p

#1068 Remove _Patch104p suffix from some INI definitions
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Patch104p

#1070 Improve exbinarystream32 texture
  Patch104pZH/GameFilesEdited/Art/Textures/NoMip/exbinarystream32.psd
  Patch104pZH/ModBundleItems.json
Labels: Enhancement, Minor

#1060 Fix up Empty China Troopcrawler
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaMiscUnit.ini
Labels: Enhancement, Minor

#1057 Add Patch104p keyword to Listening Outpost change comments
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Patch104p

#1081 Add all relevant ini and str files of maps
  Patch104pZH/GameFilesEdited/Maps/BarrenBadlands/map.ini
  Patch104pZH/GameFilesEdited/Maps/Bitter Winter/map.ini
  Patch104pZH/GameFilesEdited/Maps/Eastern Everglades/map.ini
  Patch104pZH/GameFilesEdited/Maps/FloodedPlains/map.ini
  Patch104pZH/GameFilesEdited/Maps/GC_AirGeneral/map.ini
  Patch104pZH/GameFilesEdited/Maps/GC_ChemGeneral/map.ini
  Patch104pZH/GameFilesEdited/Maps/GC_ChinaBoss/map.ini
  Patch104pZH/GameFilesEdited/Maps/GC_LaserGeneral/map.ini
  Patch104pZH/GameFilesEdited/Maps/GC_NukeGeneral/map.ini
  Patch104pZH/GameFilesEdited/Maps/Hovercraft/map.ini
  Patch104pZH/GameFilesEdited/Maps/Iron Dragon/map.ini
  Patch104pZH/GameFilesEdited/Maps/Lights Out/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_CHI01/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_CHI02/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_CHI03/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_CHI05/Map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_CHI05_END/Map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA01/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA01/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_GLA02/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA02_CINE/Map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA02_CINE/Map.str
  Patch104pZH/GameFilesEdited/Maps/MD_GLA03/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA03_CINE/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA03_CINE/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_GLA03_END/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA03_END/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_GLA04/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA04/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_GLA04_INTRO/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA04_INTRO/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_GLA04_Sound/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA04_Sound/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_GLA05/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_GLA05/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_USA01/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA01/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_USA01_CINE/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA01_CINE/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_USA02/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA03/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA03/map.str
  Patch104pZH/GameFilesEdited/Maps/MD_USA03_CINE/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA03_END/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA03_END1/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA03_Intro/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA04/Map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA04_CINE/map.ini
  Patch104pZH/GameFilesEdited/Maps/MD_USA05/map.ini
  Patch104pZH/GameFilesEdited/Maps/MapCache.ini
  Patch104pZH/GameFilesEdited/Maps/Mountain Guns/map.ini
  Patch104pZH/GameFilesEdited/Maps/Red Rock/map.ini
  Patch104pZH/GameFilesEdited/Maps/Rocky Rampage/map.ini
  Patch104pZH/GameFilesEdited/Maps/ShellMapMD/map.ini
  Patch104pZH/GameFilesEdited/Maps/USA05_EndsConflict_INTRO_N/map.ini
  Patch104pZH/GameFilesEdited/Maps/Victory Valley/map.ini
  Patch104pZH/GameFilesEdited/Maps/Winding River/map.ini
  Patch104pZH/ModBundleItems.json
Labels: Task

#1075 Update Patriot test map
  Maps/SkirmishOnly/!SkirmishTestPatriotBinaryDataStream/!SkirmishTestPatriotBinaryDataStream.map
Labels: Documentation

#1087 Fix: Immortal Stealthed Objects Which Draw Fire Flying Above Townes Base Entrances
  Patch104pZH/GameFilesEdited/Maps/GC_LaserGeneral/map.ini
Labels: Bug, Minor

#1078 Fix: Visible Permanent Muzzle Flash When Placing First Fire Base
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1084 Fix: B2 Does Sharp Turn When Carpet Bombing While Moving Diagonally
  Patch104pZH/GameFilesEdited/Data/INI/Locomotor.ini
Labels: Bug, Design, Major

#1085 Fix: Granger Fails To Call In Carpet Bomber In Generals' Challenge
  Patch104pZH/GameFilesEdited/Maps/GC_AirGeneral/map.ini
Labels: Bug, Minor

#1080 Fix: Destroyed Listening Outpost Radar Dish Spawns In Air, Has Very Low Weight
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Design, Minor

#1076 Change: Use Different Explosion Effect For Passive Demogen Destruction Weapon
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Major

#1074 Fix: Scud Launcher With Demolitions Upgrade Deals Full Explosion Damage When Destroyed By Enemy
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
Labels: Bug, Minor

#1086 Fix: Kassad Bare Stinger Troopers Are Unselectable
  Patch104pZH/GameFilesEdited/Maps/GC_Stealth/map.ini
Labels: Bug, Minor

#1088 Fix: Stinger Trooper Walk Animation Shortly After Firing
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1082 Tweak: Crushed Terrorist Effect
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Minor, Experimental

#1089 Fix: z clipping particles
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Minor

#1120 Fix: z clipping particles 2
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
Labels: Bug, Minor

#1119 Document lack of MinimumAttackRange for USA Missile Defender
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Documentation

#1130 Fix: Demo Trap Flare Effect fades out smoothly
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Minor

#1144 Fix: z clipping muzzle wave particles
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Minor

#1156 Add Minigunner and Drone weapons to DPS calculator sheet
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
Labels: Documentation

#1155 Change: Reduce USA Burton shroud range from 500 to 400
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Controversial, Minor

#1154 Fix: Use regular size Muzzle Flash effects for China Battlemaster Tank
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Minor

#1153 Change: Match level up XP of GLA Combat Bike with Jarmen Kell
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Design, Controversial, Minor

#1122 Fix: Nuke Cannon Shell Detonation Effect Has Offset
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Minor

#1180 Fix: Added the MiG's unused low fuel voice event
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1179 Change: Add Blue Missile Defender Texture From CCG
  Patch104pZH/GameFilesOptional/Art/Textures/zhca_nithunter.tga
  Patch104pZH/ModBundleItems.json
Labels: Design, NProject, Optional

#1178 Change: Auto Reload Battery When Idle
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Minor

#1170 Fix: Stealth General Saboteur Can Level Up
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor, NProject

#1163 Fix: Crusader Wreck Spawned Before Model Disappears
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Bug, Minor, NProject

#1200 Add Patch104p keyword to old changes
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
  Patch104pZH/GameFilesEdited/Data/INI/Locomotor.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionProp.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Documentation

#1220 Fix: Prevent Pilots From Entering Humvees Without Promoting Them
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Controversial, Unit AI, Major

#1136 Change: GLA Bomb Truck no longer reveals itself in close proximity of its attack target
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Design, Controversial, Minor

#1199 Change: Increase GattlingTankGun ContinuousFireCoast from 1000 to 2000 ms
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Minor

#1126 Add object experience document
  Patch104pZH/Design/Balancing/object_experience.ods
Labels: Documentation

#1096 Fix: Spawn SCUD Storm Hole Worker after Toxin Puddle disappears - after 30 seconds instead of 20 seconds
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLASystem.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Minor

#1234 Add rubble texture to draw damaged textures with
  Patch104pZH/Design/Texture/stone_pebbles_seamless_texture.png
  Patch104pZH/Design/Texture/stone_pebbles_seamless_texture.psd
Labels: Patch104p

#1231 Fix: GLA Battle Bus front window on damaged texture
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/uvbattbus_d.psd
Labels: Bug, Minor

#1226 Fix: Remove wheel from chassis of Overlord Tank
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/nvovrlrd.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/nvovrlrd_d.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/nvovrlrd_d1.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/nvovrlrd_u.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/nvovrlrd_ud.psd
  Patch104pZH/ModBundleItems.json
Labels: Enhancement, Minor, Optional

#1228 Fix: GLA Scorpion texture glitches
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/uvlitetank.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/uvlitetank_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/uvlitetank_d1.psd
Labels: Bug, Minor

#1239 Fix: Add nbptower_e texture
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/nbptower_e.psd
  Patch104pZH/GameFilesEdited/Art/W3D/NBPTower_E.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NBPTower_EN.W3D
Labels: Bug, Minor

#1237 Fix duplicate BioBomb ModuleTag names
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Patch104p

#1260 Fix: Internet Center select audio
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1273 Update EVA sound copies with fixed versions and simplify their language setup
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eusdrnup.wav
  Patch104pZH/ModBundleItems.json
Labels: Patch104p

#1282 Fix: SaboteurVoiceCreate type
  Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
Labels: Bug, Minor

#1281 Fix: TechnicalVoiceDie limit and priority
  Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
Labels: Bug, Minor

#1288 Fix: Level 3 Spectre Gunship audio
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
Labels: Bug, Minor

#1289 Fix: Level 2 and 3 Spectre Gunship damage state animation transitions
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
Labels: Bug, Minor

#1303 Add new seamless rubble textures
  Patch104pZH/Design/Texture/rubble_core_seamless.psd
  Patch104pZH/Design/Texture/rubble_grey_seamless.psd
  Patch104pZH/Design/Texture/rubble_stone_pebbles_seamless.psd
  Patch104pZH/Design/Texture/stone_pebbles_seamless_texture.png
Labels: Patch104p
