Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2022-07, with the labels that each got.

#680 Disable Suicide Button on Demo GLA Combat Bike
  Patch104pZH/Design/Changes/game_fixes.md
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
Labels: Design

#407 Fix: Non-Vanilla USA Avengers Benefit From Composite Armor
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Design, Controversial

#696 Add Weapon DPS Calculator spreadsheet(s) with Quad Cannon values
  Patch104pZH/Design/Balancing/readme.txt
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
  Patch104pZH/Design/Balancing/weapon_dps_calculator.xlsx
Labels: Documentation

#698 Add test map for Terrorist crushing
  Maps/SkirmishOnly/!SkirmishTerroristCrushTest/!SkirmishTerroristCrushTest.map
  Maps/SkirmishOnly/!SkirmishTerroristCrushTest/!SkirmishTerroristCrushTest.tga
Labels: Documentation

#316 Changed Demo Terrorist suicide flags to match other faction's terrorists.
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
Labels: Bug, OngoingDiscussion, Controversial

#699 Remove 200 extra damage prior Gamma Upgrade from Toxin Terrorists
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Design, Controversial

#695 Fix toxin terrorist suicide extra damage and glitches before Anthrax Gamma upgrade
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
Labels: Bug, Controversial

#700 Add test map for GLA Terrorist over China Mines
  Maps/SkirmishOnly/!SkirmishTerroristMinesTest/!SkirmishTerroristMinesTest.map
  Maps/SkirmishOnly/!SkirmishTerroristMinesTest/!SkirmishTerroristMinesTest.tga
Labels: Documentation

#701 Unqiue Module Tag for Cash Bounty Module
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
Labels: Bug

#697 Separate crushable death from suicide death for all GLA Terrorists and apply a bit of damage when crushing them
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial

#711 Minor update for terrorist test maps
  Maps/SkirmishOnly/!SkirmishTerroristCrushTest/!SkirmishTerroristCrushTest.map
  Maps/SkirmishOnly/!SkirmishTerroristMinesTest/!SkirmishTerroristMinesTest.map
Labels: Documentation

#712 Add test map for Drop Zone Cargo Planes
  Maps/SkirmishOnly/!SkirmishDropZoneCargoPlaneTest/!SkirmishDropZoneCargoPlaneTest.map
  Maps/SkirmishOnly/!SkirmishDropZoneCargoPlaneTest/!SkirmishDropZoneCargoPlaneTest.tga
Labels: Documentation

#725 Change: Lotus XP Requirements And Rewards (#413)
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial

#722 Add Lazr_AmericaPatriotBattery to DPS calculator
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
  Patch104pZH/Design/Balancing/weapon_dps_calculator.xlsx
Labels: Documentation

#679 Revert all cost and time changes of original 104 plus
  Patch104pZH/Design/Changes/game_balance_legacy104p.md
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/SpecialPower.ini
  Patch104pZH/GameFilesEdited/Data/INI/Upgrade.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design

#373 Fix: Laser Turret Has 1 Extra Shot When Assisting Or Engaging Airborne Targets Than Intended
  Patch104pZH/Design/Tasks/commy2_tasks.txt
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Controversial

#759 Remove obsolete Chem_PoisonFieldGammaLarge OCL from Chem_GLAInfantryTerrorist
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
Labels: Minor

#760 Update terrorist test maps
  Maps/SkirmishOnly/!SkirmishTestTerroristCrush/!SkirmishTestTerroristCrush.map
  Maps/SkirmishOnly/!SkirmishTestTerroristMines/!SkirmishTestTerroristMines.map
Labels: Documentation

#766 Update terrorist test map with a few more units
  Maps/SkirmishOnly/!SkirmishTestTerroristMines/!SkirmishTestTerroristMines.map
Labels: Documentation

#764 Adds status requirement to Terrorist death weapons
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Critical

#765 Reduce ambient audio loop range of Helix helicopter to reasonable distance
  Patch104pZH/GameFilesEdited/Data/INI/SoundEffects.ini
Labels: Design, Controversial, Minor

#776 Update terrorist test map
  Maps/SkirmishOnly/!SkirmishTestTerroristMines/!SkirmishTestTerroristMines.map
Labels: Documentation

#788 Fix broken binary stream effect
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Bug

#768 Change Tank China Hacker price from 780 to 625
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#769 Change China Hackers build time from 20 to 15 seconds
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#770 Change China Hackers experience value from 50 100 150 400 to 50 60 80 100
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#771 Change China Regular Hacker experience required from 0 100 300 500 to 0 100 250 400
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#772 Change China Regular Hacker hack interval in Internet Center from 1800 to 1600 ms
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#773 Change China Hacker movement speed by +25%
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#785 Change China Command Center door time from 3000 to 1500 ms
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Major

#786 Change China War Factory door time from 4000 to 3300 ms
  Patch104pZH/GameFilesArt/Faction/Art/W3D/NBWarFact_A8.W3D
  Patch104pZH/GameFilesArt/Faction/Art/W3D/NBWarFact_A8D.W3D
  Patch104pZH/GameFilesArt/Faction/Art/W3D/NBWarFact_A8E.W3D
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Major

#787 Change USA War Factory door time from 3250 to 3300 ms
  Patch104pZH/GameFilesArt/Faction/Art/W3D/ABWarFact_A8.W3D
  Patch104pZH/GameFilesArt/Faction/Art/W3D/ABWarFact_A8D.W3D
  Patch104pZH/GameFilesArt/Faction/Art/W3D/ABWarFact_A8E.W3D
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Minor

#795 Fix: Demo General Drops Blue Anthrax Bomb Despite Lack of Anthrax Beta Upgrade
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Design

#791 Fix: Sat Hack 1 Fails To Reveal Newly Built Command Centers
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug

#803 Fix wrong bonus logic in DPS Calculator
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
  Patch104pZH/Design/Balancing/weapon_dps_calculator.xlsx
Labels: Documentation

#798 Fix test map for Toxin General promotions
  Maps/SkirmishOnly/!SkirmishTestPromotionsTOX/!SkirmishTestPromotionsTOX.map
Labels: Documentation

#797 Add test map for Black Lotus Vehicle Hack
  Maps/SkirmishOnly/!SkirmishTestLotusVehicleHack/!SkirmishTestLotusVehicleHack.map
  Maps/SkirmishOnly/!SkirmishTestLotusVehicleHack/!SkirmishTestLotusVehicleHack.tga
Labels: Documentation
