Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2022-11, with the labels that each got.

#1419 Fix: Missing construction sounds
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1404 Add snow texture
  Patch104pZH/Design/Texture/snow_1_seamless.psd
Labels: Patch104p

#1422 Fix: Added missing shadow to the fat guy with the tank top.
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
Labels: Bug, Minor, Patch104p

#1429 Change: Removed duplicate command set fields from Black Lotus.
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Minor

#1430 Change: Removed duplicate fear voice audio fields from the Pathfinder.
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Minor

#1431 Change: Removed duplicate portrait and button image fields from the Nuclear Missile Silo.
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Minor

#1432 Change: Removed duplicate shadow fields from the MiG and other miscellaneous objects.
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianProp.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Minor

#1433 Change: Removed duplicate placement view angle fields from the China and USA Command Centers.
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Minor

#1434 Change: Removed duplicate cursor name fields from the particle cannon launch command buttons.
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
Labels: Minor

#1435 Change: Removed duplicate priority / control fields from various sound effects.
  Patch104pZH/GameFilesEdited/Data/INI/SoundEffects.ini
Labels: Minor

#1436 Change: Removed a duplicate attack field from the Aurora Bomber creation audio event.
  Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
Labels: Minor

#1437 Change: Removed duplicate projectile detonation effect fields from the Humvee and Hellfire missile weapons.
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Minor

#1438 Change: Removed a duplicate delay between shots field from the Laser Crusader's weapon.
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Minor

#1439 Change: Removed a duplicate research sound field from the Arm the Mob upgrade.
  Patch104pZH/GameFilesEdited/Data/INI/Upgrade.ini
Labels: Minor

#1440 Change: Removed a duplicate command set item field from the GLA Stealth General's Battle Bus.
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
Labels: Minor

#1441 Change: Removed duplicate armour fields from various armour sets.
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
Labels: Minor

#1413 Change: Enable and fix audio for USA Battle Drone repairs
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/gsparksa.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/gsparksb.wav
  Patch104pZH/GameFilesEdited/Data/INI/SoundEffects.ini
  Patch104pZH/ModBundleItems.json
Labels: Enhancement, Minor

#1402 Fix: Streamline drift velocity of prominent smoke and steam particles
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Minor

#1442 Change: Removed duplicate fields from various civilian / system objects.
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianProp.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Minor

#1443 Change: Removed duplicate crush data from the Civilian Humvee.
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Minor

#1444 Change: Removed some duplicate fields from the Civilian UN Soldier.
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Minor

#1071 Fix: Recover all missing language files: fixes Gamma Terror death, Battlemaster audio lines
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/vbatsee.txt
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/vbatsee.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/vbatsee.txt
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/vbatsee.wav
  Patch104pZH/GameFilesEdited/Data/Chinese/Art/W3D/UITRST_SKNP.W3D
  Patch104pZH/GameFilesEdited/Data/Chinese/Art/W3D/UITRST_SKNP.txt
  Patch104pZH/GameFilesEdited/Data/French/Art/W3D/UITRST_SKNP.W3D
  Patch104pZH/GameFilesEdited/Data/French/Art/W3D/UITRST_SKNP.txt
  Patch104pZH/GameFilesEdited/Data/Korean/Art/W3D/UITRST_SKNP.W3D
  Patch104pZH/GameFilesEdited/Data/Korean/Art/W3D/UITRST_SKNP.txt
  Patch104pZH/ModBundleItems.json
Labels: Bug, Minor

#1455 Fix: Hacker Screams With Red Guard Voice When Killed
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
Labels: Bug, Minor, Audio

#1449 Change: Reduced poison damage received by Dragon Tanks from 25% to 20%.
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
Labels: Design, Minor

#1097 Fix: Units Shoot From Center Of Palace In Certain Model States
  Patch104pZH/GameFilesEdited/Art/W3D/UBPalace_FP9.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/UBPalace_FPX.W3D
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Major

#1457 Change: Reduce the Strategy Center's stealth detection range and S&D vision bonus
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Controversial, Minor, Nerf, USA

#1274 Fix: Set limits and priorities for air unit death sounds
  Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
Labels: Bug, Minor

#1245 Fix: atsdislab snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atsdislab_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atsdislab_es.psd
Labels: Bug, Minor, Art

#1464 Split DPS calculator sheets into separate files
  Patch104pZH/Design/Balancing/Damage/AmericaDrones.ods
  Patch104pZH/Design/Balancing/Damage/AmericaPatriotBattery.ods
  Patch104pZH/Design/Balancing/Damage/AmericaVehicleHumvee.ods
  Patch104pZH/Design/Balancing/Damage/ChinaRedguard.ods
  Patch104pZH/Design/Balancing/Damage/ChinaTankGattling.ods
  Patch104pZH/Design/Balancing/Damage/GLAInfantryStingerSoldier.ods
  Patch104pZH/Design/Balancing/Damage/GLAVehicleQuadCannon.ods
  Patch104pZH/Design/Balancing/Damage/GLAVehicleToxinTruck.ods
  Patch104pZH/Design/Balancing/Damage/Template.ods
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
Labels: Documentation, Patch104p

#1252 Fix: atdiaplate textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdiaplate.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdiaplate_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdiaplate_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdiaplate_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdiaplate_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdiaplate_s.psd
Labels: Bug, Enhancement, Minor, Art

#1246 Fix: atstratslab snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atstratslab_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atstratslab_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atstratslab_s.psd
Labels: Bug, Minor, Art

#1467 Add small movement sway to USA Chinook, Comanche
  Patch104pZH/GameFilesEdited/Data/INI/Locomotor.ini
Labels: Enhancement, Minor

#1469 Change: Reduce Drone Armor upgrade bonus of USA Battle Drone from 50% to 25%
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Controversial, Minor, Nerf, USA

#1247 Fix: attarmack, attarmack02 snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/attarmack02_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/attarmack02_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/attarmack_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/attarmack_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/attarmack_s.psd
Labels: Bug, Enhancement, Minor, Art

#1472 Add AirDroneArmor for USA Slave Drones
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Enhancement

#1251 Fix: avavnger textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avavnger.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avavnger_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avavnger_e.psd
Labels: Bug, Enhancement, Minor, Art

#1253 Fix: atconvey01 snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atconvey01_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atconvey01_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atconvey01_s.psd
Labels: Bug, Minor, Art

#1474 Fix: atconvey02 texture
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atconvey02_e.psd
Labels: Minor, Art

#1256 Fix: avcomanche textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avcomanche.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avcomanche_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avcomanche_d1.psd
Labels: Bug, Enhancement, Minor, Art

#1258 Fix: avthunderbolt texture issues
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avthunderbolt.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avthunderbolt_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avthunderbolt_d1.psd
Labels: Bug, Enhancement, Minor, Art

#1263 Fix: athqslab textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/athqslab_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/athqslab_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/athqslab_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/athqslab_es.psd
Labels: Bug, Minor, Art

#1270 Fix: avpaladin textures
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/avpaladin_d.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/avpaladin_d1.psd
Labels: Bug, Minor, Optional, Art

#1271 Fix: avraptor textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/avraptor.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/avraptor_d.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/avraptor_d1.psd
Labels: Bug, Enhancement, Minor, Optional, Art

#1279 Fix: avpowtruck textures
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/avpowtruck_d.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/avpowtruck_d1.psd
Labels: Bug, Minor, Optional, Art

#1290 Fix: nvgatttank textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/nvgatttank.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/nvgatttank_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/nvgatttank_d1.psd
Labels: Bug, Enhancement, Minor, Art

#1306 Fix: pmtorch textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/pmtorch_d.tga
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/pmtorch_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/pmtorch_n.tga
Labels: Bug, Minor, Art

#1405 Fix: abbarrslab_d textures in abbarracks w3d
  .gitignore
  Patch104pZH/Design/Scripts/w3d/abbarracks.py
  Patch104pZH/Design/Scripts/w3d/w3dfilemanager.py
  Patch104pZH/GameFilesEdited/Art/W3D/ABBarracks_D.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABBarracks_DN.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABBarracks_DNS.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABBarracks_DS.W3D
Labels: Bug, Minor, Art

#1335 Change: Add slightly pitched sounds for Air weapons of Quad Cannon, Minigunner, Gattling Tank, Gattling Turret, Laser Turret
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/SoundEffects.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Enhancement, Design

#1302 Fix: ntpwrplantslab textures
  Patch104pZH/Design/Scripts/w3d/ABBarracks.py
  Patch104pZH/Design/Scripts/w3d/NBPwrPlant.py
  Patch104pZH/Design/Scripts/w3d/NBPwrPtI.py
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntpwrplantslab.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntpwrplantslab_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntpwrplantslab_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntpwrplantslab_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntpwrplantslab_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntpwrplantslab_s.psd
  Patch104pZH/GameFilesEdited/Art/W3D/NBPwrPlant_E.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NBPwrPlant_EN.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NBPwrPtI_E.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NBPwrPtI_EN.W3D
Labels: Bug, Enhancement, Minor, Art

#1487 Change: Added damage transition effect to the A10.
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Enhancement, Minor, USA

#1406 Fix: atbarrslab textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atbarrslab_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atbarrslab_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atbarrslab_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atbarrslab_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atbarrslab_s.psd
Labels: Bug, Minor, Art

#1407 Fix: atdoor textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdoor_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atdoor_s.psd
Labels: Bug, Enhancement, Minor, Art
