Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2022-12, with the labels that each got.

#1492 Fix: The EMP Patriot now uses the correct model during construction and sale
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor, USA

#1489 Change: Added scorch effects to nuclear explosions.
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
Labels: Enhancement, Minor

#1481 Fix: Reduce delay of USA Comanche final death explosion
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Enhancement, Minor

#1445 Fix: atventwall02, atventwall03, atventwall04 textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall02_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall02_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall03_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall03_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall04_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall04_e.psd
Labels: Minor, Art

#1450 Fix: atcemblock02 textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atcemblock02_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atcemblock02_es.psd
  Patch104pZH/GameFilesOriginalCCG/Art/Textures/atcemblock02_e.dds
  Patch104pZH/GameFilesOriginalCCG/Art/Textures/atcemblock02_es.dds
Labels: Enhancement, Minor, Art

#1506 Fix: atcemblock02 textures (2)
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atcemblock02_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atcemblock02_es.psd
Labels: Minor, Art

#1459 Fix: atmetal02 textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atmetal02_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atmetal02_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atmetal02_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atmetal02_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atmetal02_s.psd
Labels: Enhancement, Minor, Art

#1507 Fix: atroofparts01 textures (2)
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_s.psd
Labels: Minor, Art

#1134 Change: Increase General Promotion reward from Black Lotus by 100%
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor, Buff, China

#1490 Change: Improved death explosion of Nuclear Missile Silo
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Minor, Buff, Nerf, China

#1131 Change: Add new sound for Demo Trap select
  .gitattributes
  Patch104pZH/Design/Audio/.gitignore
  Patch104pZH/Design/Audio/gdemsela/Imported Files/gdembeep.wav
  Patch104pZH/Design/Audio/gdemsela/Imported Files/gdisveha.wav
  Patch104pZH/Design/Audio/gdemsela/gdemsela.sesx
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/gdemsela.wav
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/SoundEffects.ini
Labels: Enhancement, Minor

#1447 Change: Remove AIRCRAFT_PATH_AROUND from small non cinematic structures
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianBuilding.ini
Labels: Design, Minor, Performance

#1510 Add Patriot test map
  Maps/SkirmishOnly/!SkirmishTestPatriot/!SkirmishTestPatriot.map
  Maps/SkirmishOnly/!SkirmishTestPatriot/!SkirmishTestPatriot.tga
Labels: Documentation

#1511 Add test map for AIRCRAFT_PATH_AROUND
  Maps/SkirmishOnly/!SkirmishTest_AIRCRAFT_PATH_AROUND/!SkirmishTest_AIRCRAFT_PATH_AROUND.map
  Maps/SkirmishOnly/!SkirmishTest_AIRCRAFT_PATH_AROUND/!SkirmishTest_AIRCRAFT_PATH_AROUND.tga
Labels: Documentation

#1495 Fix: exscorch01 texture
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/exscorch01.psd
Labels: Enhancement, Optional, Art
