Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2022-08, with the labels that each got.

#777 Change USA Paladin Composite Armor bonus to match with USA Crusader Tank bonus (200)
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
Labels: Bug, Controversial, Minor

#751 Change: Decrease China Mig reload time by 50% before Upgrade
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: OngoingDiscussion, Design

#412 Change: Reduce XP reward for regular ground tanks by 30%
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial

#808 Add spreadsheet for General Rank Unit XP comparisons
  Patch104pZH/Design/Balancing/general_rank_unit_xp.ods
Labels: Documentation

#778 Add XP reward of 5 to China Outpost and China Troopcrawler
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaMiscUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#727 Change: Increase required XP of GLA SCUD Launcher by 50% and decrease required XP of GLA Rocket Buggy by 25%
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Design, Controversial, Minor

#809 Fix missing particle effects
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Major

#783 Remove Demo GLA Terror Combat Bike suicide damage to allies before Demo Upgrade
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Controversial, Minor

#822 Add explicit HEALING values to all Armor definitions of helicopters
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Documentation

#823 Add spreadsheet for unit healing time calculations
  Patch104pZH/Design/Balancing/unit_healing_time.ods
Labels: Documentation

#827 Fix: Grant Faction Inherent Upgrades By Dummy Instead Of By Building, Version 2
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
  Patch104pZH/GameFilesEdited/Data/INI/PlayerTemplate.ini
Labels: Bug

#830 Make Dummy Upgrade Global
  Patch104pZH/GameFilesEdited/Data/INI/Upgrade.ini
Labels: Enhancement

#825 Fix inconsistent button styles in Control Bar
  Patch104pZH/GameFilesEdited/Window/ControlBar.wnd
Labels: Design, Minor

#832 Add Microwave Fix To Boss Fusion Reactor
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
Labels: Bug

#826 Change: Make Anthrax Bomb Use Color Of Anthrax Upgrade
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design

#820 Fix: Toxin Tractor Model Scrap Stages
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug

#849 Update Personal Tasks
  Patch104pZH/Design/Tasks/commy2_tasks.txt
Labels: Documentation, Task

#833 Change: Add China Propaganda Center to Prerequisite of Internet Center
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#834 Change: Add Airfield or Warfactory Prerequisites to China Speaker Tower
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#836 Change: Make USA Supply Drop Zone Cargo Plane unattackable
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Design, Major, Performance

#863 Add July 2022 1v1 faction stats
  Patch104pZH/Design/Balancing/1v1_10k_rank_stats_for_2022.html
Labels: Documentation

#839 Change: Enable Speaker Tower On Propaganda Center
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial

#670 Update game_fixes.md
  Patch104pZH/Design/Changes/game_fixes.md
Labels: Documentation

#437 Change: Make Lotus Earn XP When Hacking Vehicles
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#868 Add Superweapon test map
  Maps/Any/!TestSuperweapons/!TestSuperweapons.map
  Maps/Any/!TestSuperweapons/!TestSuperweapons.tga
  Maps/Any/!TestSuperweapons/map.ini
Labels: Documentation

#875 Update Superweapon test map
  Maps/Any/!TestSuperweapons/!TestSuperweapons.map
Labels: Documentation

#881 Add more faction stats data
  Patch104pZH/Design/Balancing/Factions/1v1_10k_rank_stats_2022.html
  Patch104pZH/Design/Balancing/Factions/1v1_10k_rank_stats_2022_size_excal_marakar_fargo_vivid.html
  Patch104pZH/Design/Balancing/Factions/1v1_10k_rank_stats_2022_size_excal_marakar_fargo_vivid_boycah_logica_scuba_dominator.html
  Patch104pZH/Design/Balancing/Factions/1v1_10k_rank_stats_2022_size_excal_marakar_fargo_vivid_boycah_logica_scuba_dominator_1.png
  Patch104pZH/Design/Balancing/Factions/1v1_10k_rank_stats_2022_size_excal_marakar_fargo_vivid_boycah_logica_scuba_dominator_2.png
  Patch104pZH/Design/Balancing/Factions/generals_zh_104_faction_ratings.xlsx
Labels: Documentation

#887 Add GLA Stinger Weapon to DPS calculator
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
  Patch104pZH/Design/Balancing/weapon_dps_calculator.xlsx
Labels: Documentation

#873 Change: Allow Supply Centers To Be Placed As Close To Supplies As Other Buildings
  Patch104pZH/GameFilesEdited/Data/INI/GameData.ini
Labels: Enhancement, Minor

#883 Change: Remove Damage Effects From Immortal Buildings
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianBuilding.ini
Labels: Design, Minor

#892 Cleanup: Remove Overwritten ObjectCreationList
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Enhancement, Minor

#867 Fix rough edges and pink color cast in Infantry decal shadows
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/shadow.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/shadowi.psd
  Patch104pZH/GameFilesOriginalZH/Art/Textures/shadow.dds
  Patch104pZH/GameFilesOriginalZH/Art/Textures/shadowi.dds
  Patch104pZH/ModBundleItems.json
Labels: Bug, Minor

#890 Add GLA Toxin Tractor to DPS calculator sheet
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
Labels: Documentation

#885 Fix: GLA Buildings are missing Fortified Structures visuals during sell
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#879 Fix: Prevent Hijacker From Stealing Combat Bike
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#889 Change: Redistribute Toxin Tractor Gamma damage bonus to stay within 50% max
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Minor

#900 Change: Increase ToxinTruckGunGamma damage from 17.5 to 18.75
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Minor

#901 Update Toxin Tractor values in DPS calculator
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
Labels: Documentation

#903 Fix: Some civilian buildings show inconsistent toxin colors
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianBuilding.ini
Labels: Bug, Minor

#871 Change: Increase China Nuke Missile damage by 20% and blasts radii by 2%, 3.3%, 4%, 4.4%, 4.7%, 20%
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Design, Controversial, Major

#880 Change: Optimize China Nuke Missile blast delays: Hits max 880 ms earlier
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Design, Controversial, Minor

#904 Fix: GLA Women Mob Members Scream With Male Voice When Poisoned
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#905 Fix: GLA Mob Members Missing Scream When Burned
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#906 Fix: Obese GLA Mob Member Uses Female Death Screams When Poisoned Or Burned
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
Labels: Bug, Minor

#910 Update game_fixes.md
  Patch104pZH/Design/Changes/game_fixes.md
Labels: Documentation

#912 Fix: Unexpected Particle Beam Resistance Glitch Caused By Patch
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Bug, Major, Patch104p

#916 Add Bugfix Documentation
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Documentation

#913 Fix: Microwave Passive Emitter Vs Stinger Site Interaction
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#807 Change: Reduce China Black Lotus level up requirements by -82%
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Controversial, Minor

#922 Update Superweapon test map
  Maps/Any/!TestSuperweapons/!TestSuperweapons.map
Labels: Documentation

#923 Add Minigunner test map
  Maps/SkirmishOnly/!SkirmishTestChinaMinigunner/!SkirmishTestChinaMinigunner.map
  Maps/SkirmishOnly/!SkirmishTestChinaMinigunner/!SkirmishTestChinaMinigunner.tga
Labels: Documentation

#938 Fix: Infantry Muzzle Flash Stuck During Transition Animations
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#939 Tweak Minigunner Recoil Animation
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
Labels: Design, Minor

#937 Fix: Bones Visible On Double Scrapped Quad Cannon
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#948 Fix: Game Performance Dropping Continuously Caused By Patch
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Bug, Blocker, Patch104p

#973 Revert: Some Toxin Tractor Death Explosion Particle Effect Changes
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor, Patch104p

#975 Fix: Listening Outpost Guard Mode Range Too Large
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#974 Fix: Add Missing Guard Mode Button To Troop Crawler And Assault Troop Crawler
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
Labels: Bug, Minor

#914 Fix: Demo General Units Unable To Suicide When Close Or Inside Buildings
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Major

#949 Replace Bomb Model Replacement
  Patch104pZH/GameFilesEdited/Art/W3D/EXCarptBmb.W3D
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Design, Major

#945 Add: Supply Lines Upgrade To Oil Derrick
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianBuilding.ini
Labels: Bug, Minor

#982 Fix: Angry Mob Deals No Damage With AK47
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Critical, Patch104p

#1000 Fix: Laser Texture
  Patch104pZH/GameFilesEdited/Art/Textures/exlaser5.dds
  Patch104pZH/GameFilesEdited/Art/W3D/ABLGCLink_L.W3D
Labels: Bug, Blocker, Patch104p

#994 Fix: Delete Immortal Aurora Wrecks Circling In Air
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1001 Fix: Broken USA Dozer Dirt Particles When Clearing Mines
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#998 Fix: SWG Particle Cannon Uses Portrait Of Normal Particle Cannon
  Patch104pZH/GameFilesEdited/Art/Textures/SASWGParticleCannon.tga
  Patch104pZH/GameFilesEdited/Art/Textures/SASWGParticleCannon_L.tga
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SAUserInterface512.INI
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Minor

#997 Fix: Nuke Battlemaster Uses Button And Portrait From Normal Battlemaster
  Patch104pZH/GameFilesEdited/Art/Textures/SNNukeBattlemaster.tga
  Patch104pZH/GameFilesEdited/Art/Textures/SNNukeBattlemaster_L.tga
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SNUserInterface512.INI
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
Labels: Design, Minor

#996 Tweak: Replace Generic Tank On USA War Factory Button With Crusader
  Patch104pZH/GameFilesEdited/Art/Textures/SAWarFactory.tga
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SAUserInterface512.INI
Labels: Design, Minor

#1003 Change: Implement Previously Unused Nuke Helix Texture
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
Labels: Design, Minor

#999 Add: Upgrade Voice For MOAB, Sentry Drone Gun, Neutron Shells And Fortified Structure
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/INI/Upgrade.ini
  Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
  Patch104pZH/ModBundleItems.json
Labels: Design, Major

#1010 Fix: Female Poison And Burned Sound Effects Use Chinese Male Sound Files
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/SoundEffects.ini
Labels: Bug, Minor

#1009 Fix: Obese GLA Mob Member Uses Female Death Screams When Killed
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
Labels: Bug, Minor

#1012 Add: Cheering Animation For Rebel
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
Labels: Design, Minor

#1013 Add: Cheering Animation For Missile Defender
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Minor

#995 Fix: Broken Angry Mob Animations
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
Labels: Bug, Minor

#1034 Add Bomb Truck test map
  Maps/SkirmishOnly/!SkirmishTestGLABombTruck/!SkirmishTestGLABombTruck.map
  Maps/SkirmishOnly/!SkirmishTestGLABombTruck/!SkirmishTestGLABombTruck.tga
Labels: Documentation

#1032 Add locomotor spreadsheet
  Patch104pZH/Design/Balancing/locomotor.ods
Labels: Documentation

#1033 Add locomotor test map
  Maps/SkirmishOnly/!SkirmishTestLocomotor/!SkirmishTestLocomotor.map
  Maps/SkirmishOnly/!SkirmishTestLocomotor/!SkirmishTestLocomotor.tga
Labels: Documentation

#1035 Add missing semicolon to INI file
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Minor

#1036 Add AmericaVehicleHumvee to dps calculator and fix math error in DPS value with reloaded weapons
  Patch104pZH/Design/Balancing/weapon_dps_calculator.ods
Labels: Documentation

#1017 Fix: Laser Texture
  Patch104pZH/GameFilesEdited/Art/Textures/exlaser5.dds
  Patch104pZH/GameFilesEdited/Art/W3D/ABLGCLink_L.W3D
Labels: Bug, Minor, Patch104p

#1018 Fix: Delete Immortal Aurora Wrecks Circling In Air
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1019 Fix: Broken USA Dozer Dirt Particles When Clearing Mines
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1022 Tweak: Replace Generic Tank On USA War Factory Button With Crusader
  Patch104pZH/GameFilesEdited/Art/Textures/SAWarFactory.tga
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SAUserInterface512.INI
Labels: Design, Minor

#1020 Fix: SWG Particle Cannon Uses Portrait Of Normal Particle Cannon
  Patch104pZH/GameFilesEdited/Art/Textures/SASWGParticleCannon.tga
  Patch104pZH/GameFilesEdited/Art/Textures/SASWGParticleCannon_L.tga
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SAUserInterface512.INI
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Minor

#1021 Fix: Nuke Battlemaster Uses Button And Portrait From Normal Battlemaster
  Patch104pZH/GameFilesEdited/Art/Textures/SNNukeBattlemaster.tga
  Patch104pZH/GameFilesEdited/Art/Textures/SNNukeBattlemaster_L.tga
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/MappedImages/TextureSize_512/SNUserInterface512.INI
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
Labels: Design, Minor

#1023 Change: Implement Previously Unused Nuke Helix Texture
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
Labels: Design, Minor

#1026 Add: Upgrade Voice For MOAB, Sentry Drone Gun, Neutron Shells And Fortified Structure
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Arabic/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Brazilian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Chinese/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/English/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/French/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/German/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Italian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Korean/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Polish/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Russian/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/ecneutup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eggardup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eumoaup.wav
  Patch104pZH/GameFilesEdited/Data/Audio/Sounds/Spanish/eusdrnup.wav
  Patch104pZH/GameFilesEdited/Data/INI/Upgrade.ini
  Patch104pZH/GameFilesEdited/Data/INI/Voice.ini
  Patch104pZH/ModBundleItems.json
Labels: Design, Major

#1031 Fix: USA AI Can Order Fuel Air Bomb And Para Drop From Supply Drop Zone Planes
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SpecialPowerObjects.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1037 Fix: Broken Angry Mob Animations
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
Labels: Bug, Minor

#1029 Fix: Obese GLA Mob Member Uses Female Death Screams When Killed
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
Labels: Bug, Minor

#1028 Fix: Female Poison And Burned Sound Effects Use Chinese Male Sound Files
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/SoundEffects.ini
Labels: Bug, Minor
