Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2022-10, with the labels that each got.

#1325 Fix: Scud Storm Building Lights Turned Off At Night Until Damaged
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1326 Fix: Scud Storm Building Snow Disappears When Damaged
  Patch104pZH/GameFilesEdited/Art/W3D/UBScudStrm_DA3NS.txt
  Patch104pZH/GameFilesEdited/Art/W3D/UBScudStrm_DA3X.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/UBScudStrm_EA3NS.txt
  Patch104pZH/GameFilesEdited/Art/W3D/UBScudStrm_EA3X.W3D
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1334 Fix: Toxin GLA Tunnel Defender double firing against ground and air targets
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
Labels: Bug, Major

#1345 Fix: Gatling Cannon Animation Speed Swapped For Medium And Fast Mode On Day Snow Maps When Badly Damaged
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1347 Fix: Slightly Damaged Gatling Cannon Appears Undamaged On Snow Maps When Firing Fast
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1348 Fix: Badly Damaged Gatling Cannon Defense Creates Smoke Clouds On Medium Fast Fire On Night Maps
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1342 Fix: Gatling Tank Has Visible Floating Bones On Night Maps
  Patch104pZH/GameFilesEdited/Art/W3D/NVGattTank.W3D
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1346 Fix: Emperor Has Visible Floating Bones When Damaged
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1344 Fix: Gatling Cannon Defense Missing Muzzle Flash When Firing At Grounded Targets
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1343 Fix: Overlord Gatling Cannon Missing Muzzle Flash When Firing At Grounded Targets
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1341 Fix: Gatling Tank Missing Muzzle Flash When Firing At Grounded Targets
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1340 Fix: Quad Cannon Missing Recoil And Muzzle Flash When Firing At Grounded Targets
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1349 Fix: Overlord Gatling Cannon Keeps Spinning Indefinitely After Firing Once
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1350 Fix: Helix Gatling Cannon Keeps Spinning Indefinitely After Firing Once
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1351 Fix: Damaged Helix Uses Wreck Texture Instead Of Damaged Texture
  Patch104pZH/GameFilesEdited/Art/W3D/NVHelixNG_D.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NVHelix_D.W3D
Labels: Bug, Design, Minor

#1229 Fix: utplates snow textures
  Patch104pZH/GameFilesOriginalCCG/Art/Textures/GenerateMip/utplates_ds.psd
  Patch104pZH/GameFilesOriginalCCG/Art/Textures/GenerateMip/utplates_es.psd
  Patch104pZH/ModBundleItems.json
Labels: Enhancement, Minor, Optional

#1236 Fix: trcobbroad texture
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/trcobbroad.psd
Labels: Bug, Minor

#1315 Fix: utscudslab snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utscudslab_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utscudslab_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utscudslab_s.psd
Labels: Bug, Minor

#1328 Add upscaled utscudslab textures
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utscudslab.tga
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utscudslab_d.tga
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utscudslab_ds.tga
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utscudslab_e.tga
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utscudslab_es.tga
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utscudslab_s.tga
  Patch104pZH/ModBundleItems.json
Labels: Enhancement, Minor, Optional

#1320 Fix: utconcroof textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utconcroof_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utconcroof_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utconcroof_es.tga
Labels: Bug, Minor

#1311 Fix: utcloth textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth_s.psd
Labels: Bug, Minor

#1312 Fix: utcloth2 textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth2_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth2_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth2_r.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/utcloth2_s.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utcloth2.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utcloth2_d.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/utcloth2_e.psd
Labels: Bug, Minor

#1355 Fix: Overlord Gatling Cannon Has Very Slow Firing Animation
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1357 Fix: Helix Gatling Cannon Has Very Slow Firing Animation
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1362 Fix missing tga texture build
  Patch104pZH/ModBundleItems.json
Labels: Patch104p

#1223 Fix: BombTruck, NukeCannon, ScudMissile, FlashBang lens flare fadeouts
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Minor

#1304 Fix: ntsuppbase snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntsuppbase_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntsuppbase_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntsuppbase_s.psd
Labels: Bug, Minor

#1305 Fix: ntwalls01, ntwalls04 snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntwalls01_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntwalls01_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntwalls04_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntwalls04_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntwalls04_s.psd
Labels: Bug, Minor

#1301 Fix: ntentry snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntentry_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntentry_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntentry_s.psd
Labels: Bug, Minor

#1300 Fix: ntdrive02 textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntdrive02.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntdrive02_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntdrive02_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntdrive02_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntdrive02_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/ntdrive02_s.psd
Labels: Bug, Minor

#1298 Fix: ntcement textures
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/ntcement_e.psd
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/ntcement_es.psd
Labels: Bug, Minor, Optional

#1283 Fix: Hide Floating Cube In Front Of Damaged Microwave Tank
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1280 Fix: atroofparts01 textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atroofparts01_es.psd
Labels: Bug, Minor

#1275 Fix: atwarfactslab textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atwarfactslab_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atwarfactslab_es.psd
Labels: Bug, Minor

#1268 Fix: atprisslab snow textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atprisslab_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atprisslab_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atprisslab_s.psd
Labels: Bug, Minor

#1264 Fix: atmetal03 snow texture
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atmetal03_s.psd
Labels: Bug, Minor

#1277 Fix: atventwall01 textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall01_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall01_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atventwall01_es.psd
Labels: Bug, Enhancement, Minor

#1267 Fix: atpanelroof3 snow texture
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atpanelroof3_ds.psd
Labels: Bug, Minor

#1266 Fix: atpanelroof textures
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atpanelroof_d.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atpanelroof_ds.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atpanelroof_e.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atpanelroof_es.psd
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/atpanelroof_s.psd
  Patch104pZH/GameFilesOriginalCCG/Art/Textures/atpanelroof_ds.dds
  Patch104pZH/GameFilesOriginalCCG/Art/Textures/atpanelroof_es.dds
Labels: Bug, Minor

#1366 Fix: Remove Boneless Effects From USA Supply Center (Day Maps Only)
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor, Performance

#1369 Fix: Remove Boneless Effects From USA Airfield (Day Maps Only)
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor, Performance

#1367 Fix: Strategy Center Fan Animation Broken On Night Maps Unless Damaged
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1370 Fix: USA Helipad Model Uses Wrong Texture In Badly Damaged State On Day Summer Maps
  Patch104pZH/GameFilesEdited/Art/W3D/ABArFrcCmd_E.W3D
Labels: Bug, Minor

#1372 Fix: Control Rods Upgrade Icon Missing From Boss Reactor
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
Labels: Bug, Minor

#1374 Change: Use New nbptower_e Texture In Propaganda Center
  Patch104pZH/GameFilesEdited/Art/W3D/NBPCenter_E.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NBPCenter_EN.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NBPCenter_ENS.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/NBPCenter_ES.W3D
Labels: Design, Minor

#1373 Fix: China Barracks Fire Bowl Particles Spawn At Center Of Building When Damaged
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1382 Fix: Factory Door Animation Damage Transitions
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1379 Fix: Remove Boneless Effects From China War Factory
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor, Performance

#1385 Fix: Worker unit spawn delay introduced by Patch
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Bug, Minor, Patch104p

#1388 Change: Use USA War Factory Crane Logic For China War Factory Crane
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1387 Fix: America War Factory Smoke Coming From Center Of Building, Spawn Smoke When Constructing Only
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Design, Major

#1171 Fix: Particle Cannon Loops Deploy Animation When Finished While Disabled
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1392 Add Supply Drop Zone Crate test map
  Maps/SkirmishOnly/!SkirmishTestDropZoneCrate/!SkirmishTestDropZoneCrate.map
  Maps/SkirmishOnly/!SkirmishTestDropZoneCrate/!SkirmishTestDropZoneCrate.tga
Labels: Documentation

#1386 Fix: Building death effects
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLABuildings.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Bug, Minor

#1395 Fix: China Power Plant Particle Effect Issues And Remove Effects Without Bones
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Major, Performance

#1398 Fix: Command Center Door Animation Damage Transitions
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1411 Remove f literal from numbers in GameData.ini
  Patch104pZH/GameFilesEdited/Data/INI/GameData.ini
Labels: Minor

#1138 Change: Improve Bomb Truck Locomotor
  Patch104pZH/GameFilesEdited/Data/INI/Locomotor.ini
Labels: Enhancement, Controversial, Minor

#1176 Fix: Technical Uses Wrong Muzzle Flash When Equipped With RPG
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1127 Update game fixes document
  Patch104pZH/Design/Changes/game_fixes.md
Labels: Documentation

#1396 Add: Smoke Pillars To Small Chimneys On Nuke General Power Plant
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
Labels: Design, Minor

#1371 Fix: Remove Boneless Effects From USA Reactor, Rename Bones And Remove Misplaced Spark Effects
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_D.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_DN.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_DNS.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_DS.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_E.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_EN.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_ENS.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_ES.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_N.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_NS.W3D
  Patch104pZH/GameFilesEdited/Art/W3D/ABPwrPlant_S.W3D
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor, Performance

#1375 Fix: USA Power Plant Construction Fence Texture On Snow Night Maps
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1376 Fix: USA Power Plant Missing Animation When Damaged On Day Maps
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1164 Fix: Pilots Can Promote Combat Bikes
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1202 Remove DisplayName from vehicle hull objects
  Patch104pZH/GameFilesEdited/Data/INI/Object/Hulk.ini
Labels: Bug, Minor

#1377 Change: Increase Beacon Limit From 3 To 5
  Patch104pZH/GameFilesEdited/Data/INI/multiplayer.ini
Labels: Design, Major

#1378 Change: Reduce LAN Countdown From 5 To 3 Seconds
  Patch104pZH/GameFilesEdited/Data/INI/multiplayer.ini
Labels: Design, Minor

#1207 Fix: Wrong positional offset of China ECM, Gattling
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Bug, Minor
