Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2023-02, with the labels that each got.

#1597 Fix: Add bomb falling sounds to ClusterMinesBomb, EMPPulseBomb
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Bug, Minor, Audio

#1591 Add garrison test map
  Maps/SkirmishOnly/!SkirmishTestGarrison/!SkirmishTestGarrison.map
  Maps/SkirmishOnly/!SkirmishTestGarrison/!SkirmishTestGarrison.tga
Labels: Documentation

#1614 Add slopes test map
  Maps/SkirmishOnly/!SkirmishTestSlopes/!SkirmishTestSlopes.map
  Maps/SkirmishOnly/!SkirmishTestSlopes/!SkirmishTestSlopes.tga
Labels: Documentation

#1634 Fix: Remove non-functional FarmerTruck
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Bug, WorldBuilder, Minor

#1623 Add Laser Tank to slopes test map
  Maps/SkirmishOnly/!SkirmishTestSlopes/!SkirmishTestSlopes.map
Labels: Documentation

#1611 Streamline KindOf flags of hulk objects
  Patch104pZH/GameFilesEdited/Data/INI/Object/Hulk.ini
Labels: Minor

#1636 Remove obsolete BattleMasterTransitionDebrisSmall effects
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
Labels: Minor

#1643 Revert: Replace Microwave Haze effect from Microwave and GPS Scrambler to avoid rendering issues on some hardware configurations 2 (#1612)
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Bug, Patch104p

#1661 Add alias in INI files for Nuke Cannon objects
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Documentation

#1666 Add alias in INI file for misspelled GPSMicrowaveScambler effect
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Documentation

#1617 Rename new scorchless weapons and effects
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Patch104p

#1619 Fix: Remove duplicate radiation field on Nuke Cannon death
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1632 Fix: Civilian FarmerChickenTruck now has correct display name
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Bug, Minor

#1639 Fix boat damage models and effects
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Minor, Art

#1640 Fix plane damage models and effects
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Minor, Art

#1653 Fix: China Nuke Cannon animation jumps while it creeps forward after firing
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1645 Fix: Set proper animation modes and flags for China Nuke Cannon
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Minor

#1657 Fix China Battlemaster and Overlord death effects
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaCINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor

#1662 Fix: (Demo) GLA Marauder death explosion no longer triggers effects on turret barrels
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1672 Fix: Set correct firing sequence on GLA Marauder with double barrel
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Minor, Buff, GLA

#1670 Change: China Overlord will always reload when idle
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Major, Buff, China

#1699 Change: GLA Scorpion Rocket will always reload when idle
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Minor

#1647 Change: Add suicide car bomb ability to Civilian AircraftCropDuster
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Enhancement, Minor

#1638 Change: Civilian Humvee1 now uses the same transition damage effects as regular Humvees
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Minor, Art

#1703 Fix: GLA Scud Storm will always fully reload
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Minor

#1705 Change: USA Comanche Rocket Pod will always reload when idle
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Major, Buff, USA

#1659 Fix: Decrease quick sink rate of USA Comanche hulk, increase slow sink rate of USA Chinook, China Helix hulks
  Patch104pZH/GameFilesEdited/Data/INI/Object/Hulk.ini
Labels: Design, Minor

#1660 Change: Remove random sink delays from hulks of USA Ambulance, China Gattling, ECM
  Patch104pZH/GameFilesEdited/Data/INI/Object/Hulk.ini
Labels: Design, Minor

#1719 Fix duplicate module name in BoatAsianFishing
  Patch104pZH/GameFilesEdited/Data/INI/Object/CivilianUnit.ini
Labels: Bug, Major, Patch104p

#1742 Ignore some asset files at some locations
  Patch104pZH/GameFilesEdited/Art/Models/.gitignore
  Patch104pZH/GameFilesEdited/Art/Textures/GenerateMip/.gitignore
  Patch104pZH/GameFilesOptional/Art/Models/.gitignore
  Patch104pZH/GameFilesOptional/Art/Textures/GenerateMip/.gitignore
Labels: Patch104p

#1711 Fix: Increase destruction delays for hulks of USA Dozer, Avenger, China Dozer, Supply Truck, Inferno Cannon, Overlord, Nuke Cannon, Helix, GLA Combat Bike, Scud Launcher to avoid deletion before object is sunk into terrain
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAMiscUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/Hulk.ini
Labels: Bug, Minor

#1712 Fix: Decrease destruction delays for hulks of USA Dozer, Humvee, Ambulance, Scout Drone, Battle Drone, China Gattling, ECM, GLA Technical(s), Quad Cannon, Scorpion, Toxin Truck, Radar Van, Rocket Buggy
  Patch104pZH/GameFilesEdited/Data/INI/Object/Hulk.ini
Labels: Minor, Performance

#1706 Fix: Stealth General Rebels no longer become or remain revealed when taking damage
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor, Buff, GLA

#1707 Fix: Remove duplicate crush effects from all variants of the China Listening Outpost
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor, Performance

#1715 Fix: Condition state formatting
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Minor

#1713 Fix: Super Weapon General now uses the correct Command Center model during construction and deconstruction
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Minor

#1714 Fix: All Scud Launcher variants now correctly show their salvage upgrades during their rubble state
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1716 Fix: The GLA Angry Mob Nexus no longer appears on the radar
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor

#1718 Change: Add damage effects to the China and GLA cargo planes
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Design, Minor

#1722 Fix: Demo GLA vehicle suicide disposition issues
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
Labels: Bug, Minor

#1726 Fix: Remove destruction delay variance on death of GLA Bomb Truck
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor
