Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2023-01, with the labels that each got.

#1516 Update game_fixes.md
  Patch104pZH/Design/Changes/game_fixes.md
Labels: Documentation

#1141 Change: Tweak USA Drone shroud ranges
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Design, Controversial, Minor, USA

#1390 Change: Reduce Supply Drop Zone crate count from 6 to 3
  Patch104pZH/GameFilesEdited/Data/INI/Crate.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Design, Minor, Performance

#1522 Add infantry test map
  Maps/SkirmishOnly/!SkirmishTestInfantry/!SkirmishTestInfantry.map
  Maps/SkirmishOnly/!SkirmishTestInfantry/!SkirmishTestInfantry.tga
Labels: Documentation

#1529 Set explicit HEALING Armor values on Battle Bus
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
Labels: Documentation

#1526 Fix: Remove Booby Trap physics to prevent pushing by weapons
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Bug, Minor, GLA

#1525 Fix: Use Jet Engine sound for China Carpet Bomber
  Patch104pZH/GameFilesEdited/Data/INI/Object/SpecialPowerObjects.ini
Labels: Minor, Audio

#1524 Fix: USA Strategy Center Gun attack issues
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Bug, Major, Buff, USA

#1528 Fix: Wrong exploded death animation of supply box carrying GLA Worker
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
Labels: Bug, Minor, Art, GLA

#1531 Fix: excontrail texture
  Patch104pZH/GameFilesEdited/Art/Textures/excontrail.dds
Labels: Minor, Art

#1523 Change: Decrease China Neutron Mines cost to 400, time to 15
  Patch104pZH/GameFilesEdited/Data/INI/Upgrade.ini
Labels: Design, Controversial, Minor, Buff, China

#1534 Revert changes to Placement View Angle of USA Barracks and USA Strategy Center
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: Patch104p

#1538 Revert Change: Put Helix Bomb Upgrade and Bomb Drop buttons on same command position
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Patch104p

#1541 Fix NukeCannonRing position offset in Helix Nuke Bomb explosion
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Minor, Patch104p

#1539 Fix: Optimize USA vehicle drone spawn positions
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Design, Minor, USA

#1540 Change: Increase Nuke Bomb damage from 300 to 400, decrease secondary damage from 50 to 20
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Minor, Buff, China

#1542 Fix: Keep disabled Helix attachment upgrade buttons in Command Set
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
Labels: Bug, Minor, China

#1533 Change: Decrease China Mines build time by 2 seconds, Neutron Mines build time by 7 seconds
  Patch104pZH/GameFilesEdited/Data/INI/Upgrade.ini
Labels: Design, Controversial, Minor, Buff, China

#1520 Fix: Missile particle gliches
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
Labels: Bug, Minor, Art

#1556 Fix: Enable toxins to shoot on USA Fire Base
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
Labels: Bug, Minor, USA

#1549 Fix: Added missing border types to USA Strategy Center's battle plan command buttons
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
Labels: Bug, Minor

#1548 Fix: Corrected wrong border types of GLA Bomb Truck command buttons
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
Labels: Bug, Minor

#1564 Fix: China Inferno Tank shell object does not always emit sound and fire storm on hit
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Bug, Major, Buff, China

#1578 Fix: Preserve Clear Mines button in GLA Worker Fake Buildings command set
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
Labels: Enhancement, Minor, GLA

#1550 Update USA Patriot test map
  Maps/SkirmishOnly/!SkirmishTestPatriot/!SkirmishTestPatriot.map
  Maps/SkirmishOnly/!SkirmishTestPatriot/!SkirmishTestPatriot.tga
Labels: Documentation

#1595 Fix: Add fire sound for building attack of USA Microwave Tank
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Minor, Audio

#1585 Fix: Wrong positional offset of GLA Battle Bus wreck
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Bug, Minor

#1583 Fix: USA Avenger Laser Turret object icons
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
Labels: WorldBuilder, Minor

#1581 Fix: USA Tomahawk missile angle jump before target hit
  Patch104pZH/GameFilesEdited/Data/INI/Object/WeaponObjects.ini
Labels: Bug, Minor

#1588 Fix: Standardize the China Dragon Tank's upgraded primary weapon's minimum range with its non-upgraded weapon
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Minor, China

#1571 Change: Worker Fake Structure command button border color from Orange to Green
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
Labels: Design, Minor, Art

#1573 Fix: Remove all Special Power Shortcut command button border colors
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
Labels: Design, Minor, Art

#1536 Change: Fine tune tank scorch sizes
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
Labels: Minor, Art

#1607 Add build times document
  Patch104pZH/Design/Balancing/build_times.ods
Labels: Documentation

#1612 Revert: Replace Microwave Haze effect from Microwave and GPS Scrambler to avoid rendering issues on some hardware configurations
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Blocker, Performance, Patch104p

#1608 Add missing Patch104p identifier in various change comments
  Patch104pZH/GameFilesEdited/Data/INI/CommandButton.ini
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AirforceGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/AmericaVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/BossGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChinaAir.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/DemoGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/FactionBuilding.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Slth_GLAUnits.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLACINEUnit.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAInfantry.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GLAVehicle.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/InfantryGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/LaserGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/StealthGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/SuperWeaponGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/TankGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/ObjectCreationList.ini
Labels: Documentation

#1615 Add gametextcompiler 1.1
  Patch104pZH/Scripts/Windows/ModTools.json
  Patch104pZH/Scripts/Windows/Setup.bat
Labels: Patch104p
