Repository TheSuperHackers/GeneralsGamePatch, pull requests merged in 2023-06, with the labels that each got.

#1950 Add new dialog events for unreferenced Generals mission speech
  Patch104pZH/Design/Changes/v1.0/1950_new_generals_mission_dialog_events.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Speech.ini
Labels: Enhancement, Minor, Audio

#1906 Add scripts and info about unused sounds and speech
  Patch104pZH/Design/Scripts/ini/sounds/duplicate_sounds.txt
  Patch104pZH/Design/Scripts/ini/sounds/duplicate_sounds_review.txt
  Patch104pZH/Design/Scripts/ini/sounds/find_sound_issues.py
  Patch104pZH/Design/Scripts/ini/sounds/invalid_sounds.txt
  Patch104pZH/Design/Scripts/ini/sounds/invalid_sounds_review.txt
  Patch104pZH/Design/Scripts/ini/sounds/sound_list.py
  Patch104pZH/Design/Scripts/ini/sounds/unused_sounds.txt
  Patch104pZH/Design/Scripts/ini/sounds/unused_sounds_review.txt
  Patch104pZH/Design/Scripts/ini/speech/duplicate_dialogevent.txt
  Patch104pZH/Design/Scripts/ini/speech/find_duplicate_dialogevent.py
  Patch104pZH/Design/Scripts/ini/speech/find_speech_issues.py
  Patch104pZH/Design/Scripts/ini/speech/generals_mission_dialog.txt
  Patch104pZH/Design/Scripts/ini/speech/generals_mission_dialog_format.txt
  Patch104pZH/Design/Scripts/ini/speech/generals_unit_descript_lin.txt
  Patch104pZH/Design/Scripts/ini/speech/generals_unit_descript_lin_format.txt
  Patch104pZH/Design/Scripts/ini/speech/generate_list.py
  Patch104pZH/Design/Scripts/ini/speech/invalid_speech.txt
  Patch104pZH/Design/Scripts/ini/speech/invalid_speech_review.txt
  Patch104pZH/Design/Scripts/ini/speech/speech_list.py
  Patch104pZH/Design/Scripts/ini/speech/unused_speech.txt
  Patch104pZH/Design/Scripts/ini/speech/unused_speech_review.txt
Labels: Documentation

#1997 Revert: Remove SELECTABLE flag from SalvageCrate (#1836)
  Patch104pZH/Design/Changes/v1.0/1675_salvage_crate_crate_flag.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Crate.ini
Labels: Bug, Minor, Patch104p

#2006 Add object limit test map
  Maps/Any/!TestObjectLimit/!TestObjectLimit.map
  Maps/Any/!TestObjectLimit/!TestObjectLimit.tga
  Maps/Any/!TestObjectLimit/map.ini
Labels: Documentation

#2007 Edit and add Superweapon test maps
  Maps/Any/!TestSuperweapons/!TestSuperweapons.map
  Maps/Any/!TestSuperweapons2/!TestSuperweapons2.map
  Maps/Any/!TestSuperweapons2/!TestSuperweapons2.tga
  Maps/Any/!TestSuperweapons2/map.ini
Labels: Documentation

#2005 Revert: TechRepairPad is deleted when destroyed (#568)
  Patch104pZH/Design/Changes/v1.0/568_reinforcement_pad_ruin_model.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Object/TechBuildings.ini
Labels: Minor, Patch104p, Art

#2008 Add Elevated Buildings Testmap
  Maps/Any/!TestAllFactionsELEVATED_50/!TestAllFactionsELEVATED_50.map
  Maps/Any/!TestAllFactionsELEVATED_50/!TestAllFactionsELEVATED_50.tga
Labels: Documentation

#2013 Update !TestAllFactions.map
  Maps/Any/!TestAllFactions/!TestAllFactions.map
Labels: Documentation

#2000 Fix: Add missing Attack Move button to China ECM Tank
  Patch104pZH/Design/Changes/v1.0/2000_ecm_attackmove_button.yaml
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
Labels: Bug, Minor, China, GUI

#2001 Change: Add Guard button to GLA Radar Van
  Patch104pZH/Design/Changes/v1.0/2000_ecm_attackmove_button.yaml
  Patch104pZH/Design/Changes/v1.0/2001_radar_van_guard_button.yaml
  Patch104pZH/GameFilesEdited/Data/INI/CommandSet.ini
Labels: Enhancement, Minor, GLA, GUI

#2011 Fix: Remove obsolete structure damage particle effects
  Patch104pZH/Design/Changes/v1.0/2011_structure_damage_effects.yaml
  Patch104pZH/GameFilesEdited/Data/INI/FXList.ini
Labels: Bug, Minor, Performance, Art

#2014 Fix: Decrease small poison field radius from 12 to 7.5
  Patch104pZH/Design/Changes/v1.0/2014_small_poison_field_radius.yaml
  Patch104pZH/Design/Changes/v1.0/851_toxin_puddle_size.yaml
  Patch104pZH/GameFilesEdited/Data/INI/ParticleSystem.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Controversial, Minor, Nerf, GLA

#2015 Change: Decrease build time of GLA Toxin Demo Trap from 16 to 8 seconds
  Patch104pZH/Design/Changes/v1.0/2015_toxin_trap_build_time.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
Labels: Design, Controversial, Minor, Buff, GLA

#2017 Update change log
  Patch104pZH/Design/Changes/v1.0/1999_particle_cannon_text.yaml
  Patch104pZH/Design/Changes/v1.0/2014_small_poison_field_radius.yaml
  Patch104pZH/ReleaseUnpacked/Changes/v1.0/AllSortedByDate.md
  Patch104pZH/ReleaseUnpacked/Changes/v1.0/AllSortedBySeverity.md
  Patch104pZH/ReleaseUnpacked/Changes/v1.0/ArtOnlySortedByFaction.md
  Patch104pZH/ReleaseUnpacked/Changes/v1.0/ChinaOnlySortedByDate.md
  Patch104pZH/ReleaseUnpacked/Changes/v1.0/ControversialOnlySortedByFaction.md
  Patch104pZH/ReleaseUnpacked/Changes/v1.0/GlaOnlySortedByDate.md
  Patch104pZH/ReleaseUnpacked/Changes/v1.0/UsaOnlySortedByDate.md
Labels: Documentation

#1899 Change: Add new cursor for ground force attack
  Patch104pZH/Design/Changes/v1.0/1899_force_attack_ground_cursor.yaml
  Patch104pZH/GameFilesEdited/Data/Cursors/SCCAttack.txt
  Patch104pZH/GameFilesEdited/Data/Cursors/SCCAttack7.ani
  Patch104pZH/GameFilesEdited/Data/Cursors/SCCAttack7.psd
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack2.ani
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack2.psd
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack3.ani
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack3.psd
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack4.ani
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack4.psd
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack5.ani
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack5.psd
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack6.ani
  Patch104pZH/GameFilesEdited/Data/Cursors/Unused/SCCAttack6.psd
  Patch104pZH/GameFilesEdited/Data/INI/Mouse.ini
  Patch104pZH/ModBundleCorePacks.json
  Patch104pZH/ModBundleFullPacks.json
  Patch104pZH/ModBundleItems.json
Labels: Enhancement, Minor, Art

#2022 Fix: Decrease small poison field object radius from 6 to 4
  Patch104pZH/Design/Changes/v1.0/2014_small_poison_field_radius.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
Labels: Bug, Minor, GLA

#1989 Change: Increase armor of China Internet Center against Particle Cannon beams by 25% and Explosion attacks by 28.5%
  Patch104pZH/Design/Changes/v1.0/1989_internet_center_armor.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Armor.ini
Labels: Design, Controversial, Major, Buff, China

#2012 Change: Increase Anthrax Gamma poison field damage bonus by 20%
  Patch104pZH/Design/Changes/v1.0/2012_anthrax_gamma_field_damage.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Design, Controversial, Minor, Buff, GLA

#2028 Fix Supply Lines bonus value on USA Supply Drop Zone crates
  Patch104pZH/Design/Changes/v1.0/1390_drop_zone_crate_count.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Crate.ini
Labels: Bug, Patch104p

#2023 Change: Prioritize larger Toxin and Radiation fields over smaller ones
  Patch104pZH/Design/Changes/v1.0/2023_hazard_field_cleanup_health_and_damage.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Object/ChemicalGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/GC_Chem_GLASystem.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/NukeGeneral.ini
  Patch104pZH/GameFilesEdited/Data/INI/Object/System.ini
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Bug, Design, Controversial, Major, Buff, China, GLA

#2032 Optimization: Minimize spawn count of DummyWeaponProjectile
  Patch104pZH/Design/Changes/v1.0/2032_dummy_weapon_attack_notification.txt
  Patch104pZH/Design/Changes/v1.0/279_dummy_weapon_attack_notification.yaml
  Patch104pZH/GameFilesEdited/Data/INI/Weapon.ini
Labels: Minor, Performance, Patch104p
